require 'java'
import 'hudson.model.Result'
require 'appspider/api_v1'
require 'appspider/api_extended_v1'
require 'publisher/message'
require 'publisher/message_builder'
require 'publisher/message_builder_factory'