require 'java'
import 'hudson.model.Result'
require 'appspider/api'
require 'appspider/api_extended'
require 'publisher/message'
require 'publisher/message_builder'
require 'publisher/message_builder_factory'